### PR TITLE
Convert to Go Modules from Godep

### PR DESCRIPTION
**Pull request by costanic**
The release notes for Go 1.14 indicate that Go Modules is production-ready and strongly recommends to use Go Modules for dependency tracking.  Since we are now using 1.14 in the snap build and in the meta build, and since the tool maestro currently uses for dependency tracking, Godep, is no longer maintained, we need to upgrade to Go Modules.

### CODE REVIEW

**Comment by costanic** [comment]
Added Do Not Merge because maestro-shell is having problems upgrading to go-modules.  Specifically, it's having trouble importing greasego, which now resides in maestro.  New plan is to move greasego back into its own repo.

**Comment by JanneKiiskila** [comment]
@costanic  - rebase needed (which might be painful), this is a super large change.

**Comment by costanic** [comment]
> @costanic - rebase needed (which might be painful), this is a super large change.

Thanks @JanneKiiskila for the heads up.  Migrating maestro to Go Modules turned into a very large task and we've had higher priority issues to work on, so that's why there's been no movement on this PR in a while.

**Comment by moonchen** [comment]
Conversion to go modules is done.

**Pull request closed without merging**
