### PR TITLE
Removed parsing/generation of self signed certs from identity.json file

### PR DESCRIPTION
**Pull request by ygoyal18**
Removed parsing and generation of self-signed certificates. Also removed the old platforms which are no longer supported.

### CODE REVIEW

**Review by x85446 — APPROVED** [review]

**Comment by ygoyal18** [comment]
Requires 2.0.3 version of pe-utils (wait-for-pelion-identity) - https://github.com/PelionIoT/pe-utils/pull/5

**Comment by ygoyal18** [comment]
Manually verified. Its backward compatible with pe-utils v2.0.2 (generated self-signed certificates) and also works with latest version pe-utils  2.0.3 (no longer generates self-signed certs). But pe-utils v2.0.3 is dependent on maestro version which has this PR (most likely > maestro v2.8.0).

**Comment by costanic** [comment]
@ygoyal18 was this just dead code?  Or is this changing something fundamental to the way we currently run maestro?

**Comment by ygoyal18** [comment]
@costanic The platforms - rp200, wwrelay are no longer supported so yes that was dead code. But I also removed the parsing of `ssl` certs and keys from the identity.json as we are now using the LwM2M certificate to establish the cloud connection.

**Comment by costanic** [comment]
> @costanic The platforms - rp200, wwrelay are no longer supported so yes that was dead code. But I also removed the parsing of `ssl` certs and keys from the identity.json as we are now using the LwM2M certificate to establish the cloud connection.

oh, so this is ok because it's actually edge-proxy that establishes communication with Pelion now, and not maestro?  Does this have any impact on the snap or linux builds, any changes need to be made there?

**Comment by ygoyal18** [comment]
@costanic I dont think so, if the services are configured to use gateways.local domain for REST requests then it should work as is.

**Review by costanic — APPROVED** [review]

**Pull request merged**
