### PR TITLE
Rename armPelionEdge to PelionIoT

### PR DESCRIPTION
**Pull request by mray190**

### CODE REVIEW

**Review by cmonr — APPROVED** [review]

**Review by CristianPrundeanuARM — APPROVED** [review]
What happened in `docs/devicedb.md`, did you change line endings?

**Comment by mray190** [comment]
@x85446 @ygoyal18 We are starting to do the work to convert everything from armPelionEdge to PelionIoT. We noticed that some of the build paths are hard coded, and therefore once this change goes into effect, all distros (snap, docker, meta) will need to change.

Just wanted to open up the discussion on when and how we wanted to move forward with this

**Comment by mray190** [comment]
PR is out of date and its easier for me to just make a new PR rather than try and adjust merge conflicts. Look for a new PR shortly

**Comment by ygoyal18** [comment]
> @x85446 @ygoyal18 We are starting to do the work to convert everything from armPelionEdge to PelionIoT. We noticed that some of the build paths are hard coded, and therefore once this change goes into effect, all distros (snap, docker, meta) will need to change.
> 
> Just wanted to open up the discussion on when and how we wanted to move forward with this

@mray190 Do we have a ticket for this work? I think we can prioritize this for next Pelion Edge release.

**Comment by cmonr** [comment]
@mray190 @ygoyal18 If they're GItHub clone paths, the internal rename symlink that GitHib maintains wrt Org names should keep it working.

**Pull request closed without merging**
