### PR TITLE
fix null dereferences found by static analysis

### PR DESCRIPTION
**Pull request by costanic**
fix a possible null dereference identified by static code analysis

### CODE REVIEW

**Comment by costanic** [comment]
CI seems unstable.  It's failing for various reasons, such as 'go' not found, or the VM failing to boot.

> ~/work/gostuff/src/github.com/armPelionEdge/maestro
> ~/work/gostuff/bin ~/work/gostuff/src/github.com/armPelionEdge/maestro
> ./build.sh: line 75: go: command not found
> ./build.sh:75: 'go build ${GOTAGS} "$@" github.com/armPelionEdge/maestro/maestro' failed with '127'

>The guest machine entered an invalid state while waiting for it
> to boot. Valid states are 'starting, running'. The machine is in the
> 'aborted' state. Please verify everything is configured
> properly and try again.

**Comment by costanic** [comment]
CI seems unstable.  It's failing for various reasons, such as 'go' not found, or the VM failing to boot.

> ~/work/gostuff/src/github.com/armPelionEdge/maestro
> ~/work/gostuff/bin ~/work/gostuff/src/github.com/armPelionEdge/maestro
> ./build.sh: line 75: go: command not found
> ./build.sh:75: 'go build ${GOTAGS} "$@" github.com/armPelionEdge/maestro/maestro' failed with '127'

>The guest machine entered an invalid state while waiting for it
> to boot. Valid states are 'starting, running'. The machine is in the
> 'aborted' state. Please verify everything is configured
> properly and try again.

**Comment by costanic** [comment]
>  jenkins_build: Waiting for machine to boot. This may take a few minutes...
> The guest machine entered an invalid state while waiting for it
> to boot. Valid states are 'starting, running'. The machine is in the
> 'aborted' state. Please verify everything is configured
> properly and try again.

**Review by CristianPrundeanuARM — APPROVED** [review]

**Review by mray190 — APPROVED** [review]

**Comment by costanic** [comment]
CI is unstable: 

> Using context: edge-jenkins
> Could not update commit status of the Pull Request on GitHub.
> org.kohsuke.github.HttpException: {"message":"Validation Failed","errors":[{"resource":"Status","code":"custom","field":"sha","message":"sha must be a 40 character SHA1"}],"documentation_url":"https://docs.github.com/rest/reference/repos#create-a-commit-status"}
> 	at org.kohsuke.github.GitHubClient.interpretApiError(GitHubClient.java:495)
> 	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:420)
> 	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:363)
> 	at org.kohsuke.github.Requester.fetch(Requester.java:74)
> 	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:1906)
> 	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.createCommitStatus(GhprbSimpleStatus.java:283)
> 	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildComplete(GhprbSimpleStatus.java:241)
> 	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:205)
> 	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:28)
> 	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:209)
> 	at org.jenkinsci.plugins.workflow.job.WorkflowRun.finish(WorkflowRun.java:610)
> 	at org.jenkinsci.plugins.workflow.job.WorkflowRun.access$800(WorkflowRun.java:137)
> 	at org.jenkinsci.plugins.workflow.job.WorkflowRun$GraphL.onNewHead(WorkflowRun.java:1037)
> 	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.notifyListeners(CpsFlowExecution.java:1473)
> 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$3.run(CpsThreadGroup.java:489)
> 	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:38)
> 	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:136)
> 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
> 	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.io.IOException: Server returned HTTP response code: 422 for URL: https://api.github.com/repos/PelionIoT/maestro/statuses/master
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1950)
> 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1945)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1944)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1514)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
> 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
> 	at org.kohsuke.github.GitHubHttpUrlConnectionClient$HttpURLConnectionResponseInfo.bodyStream(GitHubHttpUrlConnectionClient.java:197)
> 	at org.kohsuke.github.GitHubResponse$ResponseInfo.getBodyAsString(GitHubResponse.java:326)
> 	at org.kohsuke.github.GitHubResponse.parseBody(GitHubResponse.java:91)
> 	at org.kohsuke.github.Requester.lambda$fetch$1(Requester.java:74)
> 	at org.kohsuke.github.GitHubClient.createResponse(GitHubClient.java:461)
> 	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:412)
> 	... 22 more
> Caused by: java.io.IOException: Server returned HTTP response code: 422 for URL: https://api.github.com/repos/PelionIoT/maestro/statuses/master
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
> 	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
> 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
> 	at org.kohsuke.github.GitHubHttpUrlConnectionClient.getResponseInfo(GitHubHttpUrlConnectionClient.java:69)
> 	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:400)
> 	... 22 more

**Pull request merged**
